import 'dotenv/config';
import { McpServer, ResourceTemplate } from '@modelcontextprotocol/sdk/server/mcp.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import { z } from 'zod';
import { ContextLoader } from './context.loader.js';
import { team, findAgent } from './team.config.js';
import { asToolError, McpDomainError } from './errors.js';
import { audit } from './audit.service.js';
import { assertToolAllowed, assertCanCommit, assertRemoteActionDenied } from './policy.service.js';
import { getProviderForAgent, inspectProviderProfiles, generateWorkerTaskPlan } from './provider.service.js';
import { getWorkerRateLimitConfig } from './rate-limit.service.js';
import { inspectProject, readWorkspaceFile, searchWorkspace, patchWorkspaceFile } from './workspace.service.js';
import { gitStatus, gitDiff, gitLog } from './git.service.js';
import { runValidation } from './validation.service.js';
import { buildHealthReport, createFeature, updateFeature, getFeature, delegateTask, reportTask, reviewTask, startTask, provisionTaskWorkspace, getProjectStatus, formatStatus, taskStore } from './orchestrator.service.js';
import { generatePdf } from './pdf.service.js';
import { exportDesignSpec, generatePrototype } from './design.service.js';
import { enqueueWorkerTask, getWorkerQueueStatus } from './worker.queue.service.js';
import { commitTask, integrateTask } from './git.integration.service.js';

const server = new McpServer({ name: 'spidermania-spider-team', version: '2.0.0' });
const contexts = new ContextLoader();
const text = (value, isError = false) => ({ content: [{ type: 'text', text: typeof value === 'string' ? value : JSON.stringify(value, null, 2) }], isError });

async function execute(agentId, toolName, operation) {
    const startedAt = Date.now();
    try {
        assertToolAllowed(agentId, toolName);
        const result = await operation();
        await audit({ actor: agentId, tool: toolName, result: 'success', durationMs: Date.now() - startedAt });
        return text(result);
    } catch (error) {
        const safe = asToolError(error);
        await audit({ actor: agentId, tool: toolName, result: 'error', error: safe.code, durationMs: Date.now() - startedAt });
        return text(safe, true);
    }
}

const agentId = z.string().min(1);
async function taskWorkspace(taskId) {
    const task = await taskStore.get(taskId);
    if (!task) throw new McpDomainError('TASK_NOT_FOUND', 'Tarefa não encontrada.');
    return task.workspacePath;
}
server.registerTool('project.inspect', { description: 'Inspeciona stack, estrutura relevante, scripts e Git somente leitura.', inputSchema: { agentId } }, ({ agentId: actor }) => execute(actor, 'project.inspect', inspectProject));
server.registerTool('context.list', { description: 'Lista contextos sem retornar prompts completos.', inputSchema: { agentId } }, ({ agentId: actor }) => execute(actor, 'context.list', () => contexts.list()));
server.registerTool('context.read', { description: 'Lê o contexto registrado de um agente.', inputSchema: { agentId, targetAgentId: agentId } }, ({ agentId: actor, targetAgentId }) => execute(actor, 'context.read', async () => { if (actor !== targetAgentId && !['peter', 'miguel'].includes(actor)) throw new McpDomainError('TOOL_NOT_ALLOWED', 'Leitura de contexto fora do escopo do agente.'); return (await contexts.readForAgent(targetAgentId)).content; }));
server.registerTool('feature.create', { description: 'Cria feature validada; uso de Peter.', inputSchema: { agentId, title: z.string().min(1), objective: z.string().min(1), context: z.string().optional(), requirements: z.array(z.string()).optional(), acceptanceCriteria: z.array(z.string()).optional(), priority: z.enum(['low', 'normal', 'high', 'critical']).optional() } }, ({ agentId: actor, ...input }) => execute(actor, 'feature.create', () => { if (actor !== 'peter') throw new McpDomainError('TOOL_NOT_ALLOWED', 'Somente Peter cria features.'); return createFeature(input); }));
server.registerTool('feature.update', { description: 'Atualiza produto por Peter ou estado técnico por Miguel.', inputSchema: { agentId, featureId: z.string(), changes: z.record(z.string(), z.unknown()) } }, ({ agentId: actor, featureId, changes }) => execute(actor, 'feature.update', () => updateFeature(featureId, actor, changes)));
server.registerTool('feature.get', { description: 'Retorna feature, tarefas, riscos e bloqueios.', inputSchema: { agentId, featureId: z.string() } }, ({ agentId: actor, featureId }) => execute(actor, 'feature.get', () => getFeature(featureId)));
server.registerTool('team.plan_feature', { description: 'Miguel analisa uma feature com loop de refinamento controlado.', inputSchema: { agentId, featureId: z.string() } }, ({ agentId: actor, featureId }) => execute(actor, 'team.plan_feature', async () => { if (actor !== 'miguel') throw new McpDomainError('TOOL_NOT_ALLOWED', 'Somente Miguel planeja features do time.'); const result = await getFeature(featureId); const context = (await contexts.readForAgent('miguel')).content; return { iterations: getWorkerRateLimitConfig().promptLoopMax, plan: await generateWorkerTaskPlan({ agentId: actor, task: { objective: result.feature.objective, scope: result.feature.context, allowedPaths: [], }, context }) }; }));
server.registerTool('task.delegate', { description: 'Miguel delega tarefa a especialista com orientações de engenharia.', inputSchema: { agentId, assignedTo: z.string(), featureId: z.string(), objective: z.string().min(1), scope: z.string().optional(), allowedPaths: z.array(z.string()).optional(), forbiddenPaths: z.array(z.string()).optional(), expectedOutput: z.string().optional(), engineeringGuidance: z.array(z.string()).optional(), validationCommands: z.array(z.string()).optional(), riskLevel: z.enum(['low', 'normal', 'high', 'critical']).optional() } }, ({ agentId: assignedBy, ...input }) => execute(assignedBy, 'task.delegate', () => delegateTask({ ...input, assignedBy })));
server.registerTool('get_engineering_guidance', { description: 'Miguel consulta feedback e preferências de engenharia de Davi relevantes para uma tarefa.', inputSchema: { agentId, task: z.string().min(1), targetAgentId: z.string().optional() } }, ({ agentId: actor, task, targetAgentId }) => execute(actor, 'get_engineering_guidance', async () => { if (actor !== 'miguel') throw new McpDomainError('TOOL_NOT_ALLOWED', 'Somente Miguel consulta as preferências para delegação.'); const { buscarPreferenciasParaAgente } = await import('../service/ia.service.js'); return buscarPreferenciasParaAgente(targetAgentId || 'miguel', task); }));
server.registerTool('task.report', { description: 'Especialista entrega resultado estruturado a Miguel.', inputSchema: { agentId, taskId: z.string(), summary: z.string(), filesChanged: z.array(z.string()).optional(), validationResults: z.array(z.string()).optional(), risks: z.array(z.string()).optional(), status: z.string().optional() } }, ({ agentId: actor, ...input }) => execute(actor, 'task.report', () => reportTask({ ...input, agentId: actor })));
server.registerTool('task.review', { description: 'Miguel revisa uma entrega e a aprova ou solicita alterações.', inputSchema: { agentId, taskId: z.string(), approved: z.boolean() } }, ({ agentId: actor, taskId, approved }) => execute(actor, 'task.review', () => reviewTask(taskId, actor, approved)));
server.registerTool('task.enqueue', { description: 'Miguel coloca uma tarefa na fila de execução automática do worker.', inputSchema: { agentId, taskId: z.string() } }, ({ agentId: actor, taskId }) => execute(actor, 'task.enqueue', () => enqueueWorkerTask(taskId, actor)));
server.registerTool('task.queue_status', { description: 'Retorna workers ativos e tarefas aguardando execução.', inputSchema: { agentId } }, ({ agentId: actor }) => execute(actor, 'task.queue_status', getWorkerQueueStatus));
server.registerTool('task.start', { description: 'Especialista inicia uma tarefa que lhe foi delegada.', inputSchema: { agentId, taskId: z.string() } }, ({ agentId: actor, taskId }) => execute(actor, 'task.start', () => startTask(taskId, actor)));
server.registerTool('task.provision_workspace', { description: 'Cria uma branch e um worktree isolado para a tarefa.', inputSchema: { agentId, taskId: z.string() } }, ({ agentId: actor, taskId }) => execute(actor, 'task.provision_workspace', () => provisionTaskWorkspace(taskId, actor)));
server.registerTool('worker.plan_task', { description: 'Gera um plano técnico usando o provider worker e o contexto do especialista.', inputSchema: { agentId, taskId: z.string() } }, ({ agentId: actor, taskId }) => execute(actor, 'worker.plan_task', async () => { const task = await taskStore.get(taskId); if (!task || task.assignedTo !== actor) throw new McpDomainError('TASK_NOT_ALLOWED', 'A tarefa não pertence a este agente.'); const context = (await contexts.readForAgent(actor)).content; return generateWorkerTaskPlan({ task, context }); }));
server.registerTool('code.search', { description: 'Busca texto no workspace da tarefa ou no projeto.', inputSchema: { agentId, pattern: z.string().min(1), directory: z.string().optional(), taskId: z.string().optional() } }, ({ agentId: actor, pattern, directory, taskId }) => execute(actor, 'code.search', async () => searchWorkspace(pattern, directory, taskId ? await taskWorkspace(taskId) : undefined)));
server.registerTool('file.read', { description: 'Lê arquivo permitido no workspace da tarefa.', inputSchema: { agentId, path: z.string(), taskId: z.string().optional() } }, ({ agentId: actor, path, taskId }) => execute(actor, 'file.read', async () => readWorkspaceFile(path, taskId ? await taskWorkspace(taskId) : undefined)));
server.registerTool('file.patch', { description: 'Aplica substituição única em caminho autorizado por tarefa ativa.', inputSchema: { agentId, taskId: z.string(), path: z.string(), oldText: z.string(), newText: z.string(), allowedPaths: z.array(z.string()) } }, ({ agentId: actor, taskId, path, oldText, newText, allowedPaths }) => execute(actor, 'file.patch', async () => { const task = await taskStore.get(taskId); if (!task || !['assigned', 'in_progress'].includes(task.status) || task.assignedTo !== actor) throw new McpDomainError('TASK_BLOCKED', 'A tarefa não está ativa para este agente.'); if (!task.workspacePath) throw new McpDomainError('WORKTREE_NOT_FOUND', 'Provisione o workspace da tarefa antes de editar.'); if (!task.allowedPaths.includes(path) || !allowedPaths.includes(path)) throw new McpDomainError('PATH_NOT_ALLOWED', 'Caminho não autorizado pela tarefa.'); return patchWorkspaceFile({ inputPath: path, oldText, newText, allowedPaths, rootOverride: task.workspacePath }); }));
server.registerTool('validation.run', { description: 'Executa uma validação cadastrada no workspace da tarefa.', inputSchema: { agentId, name: z.enum(['test', 'syntax', 'mcp']), taskId: z.string().optional() } }, ({ agentId: actor, name, taskId }) => execute(actor, 'validation.run', async () => runValidation(name, 30_000, taskId ? await taskWorkspace(taskId) : undefined)));
server.registerTool('git.status', { description: 'Git status somente leitura do projeto ou worktree da tarefa.', inputSchema: { agentId, taskId: z.string().optional() } }, ({ agentId: actor, taskId }) => execute(actor, 'git.status', async () => taskId ? gitStatus(await taskWorkspace(taskId)) : gitStatus()));
server.registerTool('git.diff', { description: 'Diff somente leitura em caminho permitido.', inputSchema: { agentId, path: z.string().optional(), staged: z.boolean().optional(), taskId: z.string().optional() } }, ({ agentId: actor, path = '.', staged = false, taskId }) => execute(actor, 'git.diff', async () => gitDiff(path, staged, taskId ? await taskWorkspace(taskId) : undefined)));
server.registerTool('git.log', { description: 'Histórico Git somente leitura com limite.', inputSchema: { agentId, limit: z.number().optional(), taskId: z.string().optional() } }, ({ agentId: actor, limit = 20, taskId }) => execute(actor, 'git.log', async () => gitLog(limit, taskId ? await taskWorkspace(taskId) : undefined)));
server.registerTool('git.remoteAction', { description: 'Bloqueada por padrão; exige autorização explícita.', inputSchema: { agentId, action: z.string() } }, ({ agentId: actor }) => execute(actor, 'git.remoteAction', async () => assertRemoteActionDenied()));
server.registerTool('git.prepareCommit', { description: 'Prepara commit local somente para Miguel; execução final ainda exige revisão.', inputSchema: { agentId, paths: z.array(z.string()).min(1), message: z.string().regex(/^(feat|fix|refactor|test|docs|perf|build|ci|style|chore|revert)(\([^)]+\))?: .+/) } }, ({ agentId: actor, paths, message }) => execute(actor, 'git.prepareCommit', async () => { assertCanCommit(actor); return { prepared: false, message, paths, note: 'Staging/commit deve ser executado após revisão explícita de Miguel.' }; }));
server.registerTool('git.commit_task', { description: 'Miguel cria commit local apenas da task validada e seus caminhos autorizados.', inputSchema: { agentId, taskId: z.string(), message: z.string().regex(/^(feat|fix|refactor|test|docs|perf|build|ci|style|chore|revert)(\([^)]+\))?: .+/) } }, ({ agentId: actor, taskId, message }) => execute(actor, 'git.commit_task', async () => { assertCanCommit(actor); return commitTask(taskId, message); }));
server.registerTool('git.integrate_task', { description: 'Miguel integra uma branch local validada no workspace principal.', inputSchema: { agentId, taskId: z.string() } }, ({ agentId: actor, taskId }) => execute(actor, 'git.integrate_task', async () => { assertCanCommit(actor); return integrateTask(taskId); }));
server.registerTool('audit.get', { description: 'Retorna resumo seguro do projeto para Miguel.', inputSchema: { agentId } }, ({ agentId: actor }) => execute(actor, 'audit.get', getProjectStatus));
server.registerTool('documentation.request', { description: 'Solicita documentação confirmada a Ben.', inputSchema: { agentId, featureId: z.string(), confirmedFacts: z.array(z.string()).min(1) } }, ({ agentId: actor, featureId, confirmedFacts }) => execute(actor, 'documentation.request', async () => ({ requestedBy: actor, assignedTo: 'ben', featureId, confirmedFacts })));
server.registerTool('documentation.report', { description: 'Entrega documentação com fontes e lacunas.', inputSchema: { agentId, featureId: z.string(), documents: z.array(z.string()), sourcesVerified: z.array(z.string()), gaps: z.array(z.string()).optional() } }, ({ agentId: actor, ...input }) => execute(actor, 'documentation.report', async () => { if (actor !== 'ben') throw new McpDomainError('TOOL_NOT_ALLOWED', 'Somente Ben entrega documentação.'); return input; }));
server.registerTool('documentation.generate_pdf', { description: 'Ben gera e verifica um PDF documental dentro do workspace.', inputSchema: { agentId, featureId: z.string(), title: z.string().min(1), sections: z.array(z.object({ heading: z.string().min(1), content: z.string().min(1) })).min(1), outputPath: z.string().regex(/^reports\/[a-zA-Z0-9._-]+\.pdf$/).optional() } }, ({ agentId: actor, featureId, title, sections, outputPath }) => execute(actor, 'documentation.generate_pdf', async () => { if (actor !== 'ben') throw new McpDomainError('TOOL_NOT_ALLOWED', 'Somente Ben gera PDFs documentais.'); const pdf = await generatePdf({ title: `${title} - ${featureId}`, sections, outputPath }); return { featureId, ...pdf }; }));
server.registerTool('design.generate_prototype', { description: 'Pavitr gera uma tela/protótipo navegável HTML no workspace da tarefa.', inputSchema: { agentId, taskId: z.string(), title: z.string().min(1), outputName: z.string().optional(), screens: z.array(z.object({ id: z.string().regex(/^[a-zA-Z0-9-]+$/), heading: z.string().min(1), body: z.string().optional(), actions: z.array(z.string()).optional() })).min(1).max(20) } }, ({ agentId: actor, taskId, title, outputName, screens }) => execute(actor, 'design.generate_prototype', async () => { if (actor !== 'pavitr') throw new McpDomainError('TOOL_NOT_ALLOWED', 'Somente Pavitr gera protótipos.'); return generatePrototype({ title, outputName, screens }, await taskWorkspace(taskId)); }));
server.registerTool('design.export_spec', { description: 'Pavitr exporta a especificação estruturada das telas para futura integração Figma.', inputSchema: { agentId, taskId: z.string(), title: z.string().min(1), outputName: z.string().optional(), screens: z.array(z.object({ id: z.string().regex(/^[a-zA-Z0-9-]+$/), heading: z.string().min(1), body: z.string().optional(), actions: z.array(z.string()).optional() })).min(1).max(20) } }, ({ agentId: actor, taskId, title, outputName, screens }) => execute(actor, 'design.export_spec', async () => { if (actor !== 'pavitr') throw new McpDomainError('TOOL_NOT_ALLOWED', 'Somente Pavitr exporta especificações.'); return exportDesignSpec({ title, outputName, screens }, await taskWorkspace(taskId)); }));
server.registerTool('get_project_status', { description: 'Compatibilidade: status seguro do projeto.', inputSchema: { agentId } }, ({ agentId: actor }) => execute(actor, 'get_project_status', getProjectStatus));
server.registerTool('generate_code_health_report', { description: 'Compatibilidade: relatório Markdown do estado persistido.', inputSchema: { agentId } }, ({ agentId: actor }) => execute(actor, 'generate_code_health_report', buildHealthReport));
server.registerTool('format_progress_update', { description: 'Compatibilidade: atualização curta.', inputSchema: { agentId } }, ({ agentId: actor }) => execute(actor, 'format_progress_update', formatStatus));

server.registerResource('spiderteam-agents', 'spiderteam://agents', { mimeType: 'application/json' }, async () => ({ contents: [{ uri: 'spiderteam://agents', text: JSON.stringify(team.map(({ id, name, role, reportsTo, allowedTools, providerProfile }) => ({ id, name, role, reportsTo, allowedTools, providerProfile }))) }] }));
server.registerResource('spiderteam-project', 'spiderteam://project/summary', { mimeType: 'application/json' }, async () => ({ contents: [{ uri: 'spiderteam://project/summary', text: JSON.stringify(await getProjectStatus()) }] }));
server.registerResource('spiderteam-features', 'spiderteam://features', { mimeType: 'application/json' }, async () => ({ contents: [{ uri: 'spiderteam://features', text: JSON.stringify((await getProjectStatus()).features) }] }));
server.registerResource('spiderteam-tasks', 'spiderteam://tasks', { mimeType: 'application/json' }, async () => ({ contents: [{ uri: 'spiderteam://tasks', text: JSON.stringify((await getProjectStatus()).tasks) }] }));
server.registerResource('spiderteam-agent', new ResourceTemplate('spiderteam://agents/{agentId}', { list: undefined }), { mimeType: 'application/json' }, async (uri, variables) => ({ contents: [{ uri: uri.href, text: JSON.stringify(findAgent(String(variables.agentId)) || {}) }] }));
server.registerResource('spiderteam-context', new ResourceTemplate('spiderteam://contexts/{agentId}', { list: undefined }), { mimeType: 'text/plain' }, async (uri, variables) => ({ contents: [{ uri: uri.href, text: (await contexts.readForAgent(String(variables.agentId))).content }] }));

for (const name of ['analyze_project', 'plan_feature', 'review_delivery', 'prepare_product_report', 'delegate_backend_task', 'delegate_frontend_task', 'delegate_uiux_task', 'delegate_devops_task', 'delegate_security_task', 'delegate_quality_task', 'delegate_qa_task', 'delegate_documentation_task']) {
    server.registerPrompt(name, { description: `Fluxo reutilizável ${name}.`, argsSchema: { request: z.string().optional() } }, async ({ request = '' }) => ({ description: name, messages: [{ role: 'user', content: { type: 'text', text: `Use os contextos registrados e dados mínimos necessários. Solicitação: ${request}` } }] }));
}

console.error(`Spider-Team MCP pronto; providers: ${JSON.stringify(inspectProviderProfiles())}`);
await server.connect(new StdioServerTransport());
