export const team = [
    { id: 'peter', name: 'PeterPark', role: 'Product Manager', contextFile: '0.5_PETER_PRODUCT_MANAGER.md', reportsTo: 'davi', allowedTools: ['project.inspect', 'context.list', 'context.read', 'feature.create', 'feature.update', 'feature.get', 'task.delegate', 'audit.get'], deniedTools: ['file.patch', 'git.prepareCommit', 'git.remoteAction'], capabilities: ['product-planning', 'progress-reporting'], status: 'active', providerProfile: 'primary', canContactUser: true, canDelegate: true, canCommit: false, canPerformRemoteGitActions: false },
    { id: 'miguel', name: "Miguel O'Hara", role: 'Tech Lead', contextFile: '01_MIGUEL_TECH_LEAD.md', reportsTo: 'peter', allowedTools: ['project.inspect', 'context.list', 'context.read', 'feature.update', 'feature.get', 'team.plan_feature', 'task.delegate', 'task.report', 'task.review', 'task.enqueue', 'task.queue_status', 'code.search', 'file.read', 'file.patch', 'validation.run', 'git.status', 'git.diff', 'git.log', 'git.prepareCommit', 'git.commit_task', 'git.integrate_task', 'audit.get', 'documentation.request', 'documentation.report'], deniedTools: ['git.remoteAction'], capabilities: ['architecture', 'delegation', 'code-review', 'local-commit', 'prompt-loops'], status: 'active', providerProfile: 'worker', canContactUser: false, canDelegate: true, canCommit: true, canPerformRemoteGitActions: false },
    { id: 'otto', name: 'Superior Spider-Man', role: 'Backend Engineer', contextFile: '02_OTTO_BACKEND.md', reportsTo: 'miguel', allowedTools: ['context.read', 'code.search', 'file.read', 'file.patch', 'validation.run', 'worker.plan_task', 'git.status', 'git.diff'], deniedTools: ['git.prepareCommit', 'git.remoteAction'], capabilities: ['backend'], status: 'active', providerProfile: 'worker', canContactUser: false, canDelegate: false, canCommit: false, canPerformRemoteGitActions: false },
    { id: 'miles', name: 'Miles Morales', role: 'Frontend Engineer', contextFile: '03_MILES_FRONTEND.md', reportsTo: 'miguel', allowedTools: ['context.read', 'code.search', 'file.read', 'file.patch', 'validation.run', 'worker.plan_task', 'git.status', 'git.diff'], deniedTools: ['git.prepareCommit', 'git.remoteAction'], capabilities: ['frontend'], status: 'active', providerProfile: 'worker', canContactUser: false, canDelegate: false, canCommit: false, canPerformRemoteGitActions: false },
    { id: 'pavitr', name: 'Pavitr Prabhakar', role: 'UI/UX Designer', contextFile: '04_PAVITR_UI_UX.md', reportsTo: 'miguel', allowedTools: ['context.read', 'code.search', 'file.read', 'design.generate_prototype', 'design.export_spec'], deniedTools: ['file.patch', 'git.prepareCommit', 'git.remoteAction'], capabilities: ['uiux', 'prototyping', 'design-spec'], status: 'active', providerProfile: 'worker', canContactUser: false, canDelegate: false, canCommit: false, canPerformRemoteGitActions: false },
    { id: 'peni', name: 'Peni Parker', role: 'DevOps Engineer', contextFile: '05_PENI_DEVOPS.md', reportsTo: 'miguel', allowedTools: ['context.read', 'code.search', 'file.read', 'file.patch', 'validation.run', 'worker.plan_task', 'git.status', 'git.diff'], deniedTools: ['git.prepareCommit', 'git.remoteAction'], capabilities: ['devops', 'infrastructure'], status: 'active', providerProfile: 'worker', canContactUser: false, canDelegate: false, canCommit: false, canPerformRemoteGitActions: false },
    { id: 'spider-byte', name: 'Spider-Byte', role: 'Cybersecurity Engineer', contextFile: '06_SPIDER_BYTE_SECURITY.md', reportsTo: 'miguel', allowedTools: ['context.read', 'code.search', 'file.read', 'validation.run', 'git.status', 'git.diff'], deniedTools: ['file.patch', 'git.prepareCommit', 'git.remoteAction'], capabilities: ['security-review'], status: 'active', providerProfile: 'worker', canContactUser: false, canDelegate: false, canCommit: false, canPerformRemoteGitActions: false },
    { id: 'gwen', name: 'Gwen Stacy', role: 'Quality Engineer', contextFile: '07_GWEN_QUALITY.md', reportsTo: 'miguel', allowedTools: ['context.read', 'code.search', 'file.read', 'validation.run', 'git.status', 'git.diff'], deniedTools: ['git.prepareCommit', 'git.remoteAction'], capabilities: ['quality-strategy'], status: 'active', providerProfile: 'worker', canContactUser: false, canDelegate: false, canCommit: false, canPerformRemoteGitActions: false },
    { id: 'noir', name: 'Spider-Man Noir', role: 'QA Test Engineer', contextFile: '08_NOIR_QA.md', reportsTo: 'miguel', allowedTools: ['context.read', 'code.search', 'file.read', 'validation.run', 'git.status', 'git.diff'], deniedTools: ['git.prepareCommit', 'git.remoteAction'], capabilities: ['testing'], status: 'active', providerProfile: 'worker', canContactUser: false, canDelegate: false, canCommit: false, canPerformRemoteGitActions: false },
    { id: 'ben', name: 'Ben Reilly', role: 'Technical Writer', contextFile: '09_BEN_DOCUMENTATION.md', reportsTo: 'miguel', allowedTools: ['context.read', 'code.search', 'file.read', 'file.patch', 'documentation.generate_pdf', 'git.status', 'git.diff'], deniedTools: ['git.prepareCommit', 'git.remoteAction'], capabilities: ['documentation', 'pdf-reports'], status: 'active', providerProfile: 'worker', canContactUser: false, canDelegate: false, canCommit: false, canPerformRemoteGitActions: false }
];

export function findAgent(agentId) {
    return team.find((agent) => agent.id === agentId || agent.name === agentId) || null;
}

export const findOwner = findAgent;